[package]
name = "electrsd"
version = "0.9.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
description = "Utility to run a regtest electrs process, useful in integration testing environment"
repository = "https://github.com/RCasatta/electrsd"
documentation = "https://docs.rs/elecrtsd/"
license = "MIT"
edition = "2018"

[dependencies]
bitcoind = { git = "https://github.com/LLFourn/bitcoind.git", branch = "use_outdir" }
electrum-client = { version="0.8.0", default-features = false }
nix = { version="0.22.0", optional = true }
home = "0.5.3"
log = "0.4"

[dev-dependencies]
env_logger = "0.9"

[build-dependencies]
bitcoin_hashes = "0.10"
zip = "0.5"
ureq = "2.1"

[features]
default = ["bitcoind_0_21_1"]
trigger = ["nix"]
legacy = []

esplora_a33e97e1 = []
electrs_0_8_10 = []

bitcoind_0_21_1 = ["bitcoind/0_21_1"]
bitcoind_0_21_0 = ["bitcoind/0_21_0"]
bitcoind_0_20_1 = ["bitcoind/0_20_1"]
bitcoind_0_20_0 = ["bitcoind/0_20_0"]
bitcoind_0_19_1 = ["bitcoind/0_19_1"]
bitcoind_0_19_0_1 = ["bitcoind/0_19_0_1"]
bitcoind_0_18_1 = ["bitcoind/0_18_1"]
bitcoind_0_18_0 = ["bitcoind/0_18_0"]
bitcoind_0_17_1 = ["bitcoind/0_17_1"]
